/**
 * Project configuration file for AntHocNet Algo implementation.
 */

#ifndef IEEE_802_15_4_ANTNET_PROJECT_CONF_H
#define IEEE_802_15_4_ANTNET_PROJECT_CONF_H

#define TSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL 1

#define NETSTACK_CONF_ROUTING anthocnet_driver
#define NETSTACK_CONF_WITH_IPV6 1

#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_DBG

#define UIP_MCAST6_CONF_ENGINE 4

#endif //IEEE_802_15_4_ANTNET_PROJECT_CONF_H
